=== Pan6ora/activity-browser-online/docs/source/_static/session_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the session",
      "type": "string"
    },
    "password": {
      "description": "The password used to connect to the session",
      "type": "string"
    },
    "machines": {
      "description": "Number of machines to start",
      "type": "integer"
    },
    "ab_channel": {
      "description": "Anaconda channel to fetch Activity Browser from",
      "type": "string"
    },
    "ab_version": {
      "description": "Anaconda Activity Browser version",
      "type": "string"
    },
    "databases": {
      "description": "list of databases to use",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "description": "database name",
              "type": "string"
            },
            "filename": {
              "description": "name of the database file",
              "type": "string"
            },
            "location": {
              "description": "location of the file",
              "type": "string"
            }
          },
          "required": ["name", "filename", "location"]
        }
      ]
    },
    "plugins": {
      "description": "list of plugins to use",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "description": "plugin name",
              "type": "string"
            },
            "ab_channel": {
              "description": "anaconda channel",
              "type": "string"
            },
            "version": {
              "description": "anaconda package version",
              "type": "string"
            }
          },
          "required": ["name", "ab_channel", "version"]
        }
      ]
    },
    "projects": {
      "description": "list of projects to create",
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "description": "project name",
              "type": "string"
            },
            "databases": {
              "description": "databases to import",
              "type": "array",
              "items": [
                {
                  "description": "plugin name",
                  "type": "string"
                }
              ]
            },
            "plugins": {
              "description": "plugins to activate",
              "type": "array",
              "items": [
                {
                  "description": "plugin name",
                  "type": "string"
                }
              ]
            }
          },
          "required": ["name", "databases", "plugins"]
        }
      ]
    }
  },
  "required": [
    "name",
    "password",
    "machines",
    "ab_channel",
    "ab_version",
    "databases",
    "plugins",
    "projects"
  ]
}

=== Pan6ora/activity-browser-online/ab_online/data/sessions/example.json
{
    "name"       : "example",
    "password"   : "azerty",
    "machines"   :  1,
    "ab_channel" : "pan6ora",  
    "ab_version" : "2.7.5+pm1.0.3",
    "databases": [],
    "plugins": [],
    "projects": [
        { 
            "name" : "default",
            "databases" : [],
            "plugins"   : []
        }
    ]
}

=== Pan6ora/activity-browser-online/ab_online/includes/example_session.json
{
    "name": "example",
    "password": "azerty",
    "machines": 1,
    "ab_channel": "conda-forge",
    "ab_version": "2.9.0",
    "databases": [],
    "plugins": [],
    "projects": [
        {
            "name": "default",
            "databases": [],
            "plugins": []
        }
    ]
}
